language: node_js

node_js:
  - "stable"

cache:
  yarn: true
  directories:
    - 'node_modules'

install:
  - bundle install
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn
script:
  - yarn test