before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.19.1
  - export PATH="$HOME/.yarn/bin:$PATH"
cache:
  yarn: true
  directories:
    - "node_modules"
language: node_js
node_js:
  - "stable"
before_install: cd server
install:
  - yarn install
script:
  - yarn test