

export const ADD_COMPONENT = "ADD_COMPONENT"

export const UPDATE_COMPONENTS = "UPDATE_COMPONENTS"

export const ADD_VIEW = "ADD_VIEW"

export const SELECT_COMPONENT = "SELECT_COMPONENT"

export const EDIT_COMPONENT = "EDIT_COMPONENT"

export const SELECT_TAB = "SELECT_TAB"

export const SAVE_VIEWS = "SAVE_VIEWS"